server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mariadb://server.aptech.io:3306/spring
    username: root
    password: HBkb2012@trungvuong
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true